//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF02_ModelFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlogArticle
    {
        public System.Guid Id { get; set; }
        public string BlogId { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
    
        public virtual Blog Blog { get; set; }
    }
}
